# Site settings
title: Adventures in Coding
header-img: img/home-bg.png
email: maryobray@gmail.com
copyright_name: MaryObray
description: > # this means to ignore newlines until "baseurl:"
  A mind adventure is as good as any
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MaryObray
learn_profile: MaryObray
email_username: maryobray@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
